// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pHRIUzzCB48ekJSUhZ64j5LKGfJNfU8',
    appId: '1:557299752863:web:3e065d9a864916874f27aa',
    messagingSenderId: '557299752863',
    projectId: 'crypto-list-app-c090f',
    authDomain: 'crypto-list-app-c090f.firebaseapp.com',
    storageBucket: 'crypto-list-app-c090f.firebasestorage.app',
    measurementId: 'G-M2NWM5S5WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMbBVaHmtJE1U2zN64lgsHjY-4up2x-4',
    appId: '1:557299752863:android:84acdfbb3beb21424f27aa',
    messagingSenderId: '557299752863',
    projectId: 'crypto-list-app-c090f',
    storageBucket: 'crypto-list-app-c090f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8gtchspKJUIgCI21L88ziMwb3uJTdK8',
    appId: '1:557299752863:ios:935c8a0ca0af90824f27aa',
    messagingSenderId: '557299752863',
    projectId: 'crypto-list-app-c090f',
    storageBucket: 'crypto-list-app-c090f.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8gtchspKJUIgCI21L88ziMwb3uJTdK8',
    appId: '1:557299752863:ios:935c8a0ca0af90824f27aa',
    messagingSenderId: '557299752863',
    projectId: 'crypto-list-app-c090f',
    storageBucket: 'crypto-list-app-c090f.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pHRIUzzCB48ekJSUhZ64j5LKGfJNfU8',
    appId: '1:557299752863:web:b82c11ec595118384f27aa',
    messagingSenderId: '557299752863',
    projectId: 'crypto-list-app-c090f',
    authDomain: 'crypto-list-app-c090f.firebaseapp.com',
    storageBucket: 'crypto-list-app-c090f.firebasestorage.app',
    measurementId: 'G-9VYNPRKMCN',
  );
}
