// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:learning/repositories/crypto_coins/models/crypto_coin.dart';
import 'package:learning/repositories/crypto_coins/models/crypto_coin_details.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailsAdapter());
  }
}
